version: "2"
services:
  app:
    image: nimmis/apache-php7:latest
    volumes:
      - "./:/var/www/html"
    links:
      - otp
    build: .
    environment:
      - VIRTUAL_HOST=busassistant.xyz
      - LETSENCRYPT_HOST=busassistant.xyz
      - LETSENCRYPT_EMAIL=jackgreenhill@me.com
    network_mode: "bridge"
  otp:
    image: goabout/opentripplanner:0.19.0
    volumes:
      - "./resources/otp:/data:ro"
    command: otp --build /data --inMemory
    network_mode: "bridge"
